apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: brtrm-dev-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: ghcr.io/<your-github-org>/brtrm-dev-catalog/catalog:latest
  displayName: IP Rules Catalog
  publisher: Your Organization
  updateStrategy:
    registryPoll:
      interval: 10m
